"""Initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-26 00:00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###

    # Users table
    op.create_table(
        "users",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", pg.BYTEA, nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("(now())"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        sa.UniqueConstraint("email"),
        sa.Index("ix_users_username", "username"),
        sa.Index("ix_users_email", "email"),
    )

    # Roles table
    op.create_table(
        "roles",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.Index("ix_roles_name", "name"),
    )

    # Resources table
    op.create_table(
        "resources",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("criticality", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.Index("ix_resources_name", "name"),
    )

    # Permissions table
    op.create_table(
        "permissions",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("resource_id", pg.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_id", "action", name="uq_permission_resource_action"
        ),
        sa.Index("ix_permissions_resource_id", "resource_id"),
    )

    # Association tables
    op.create_table(
        "user_role",
        sa.Column("user_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("role_id", pg.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
        sa.Index("ix_user_role_user_id", "user_id"),
        sa.Index("ix_user_role_role_id", "role_id"),
    )

    op.create_table(
        "role_permission",
        sa.Column("role_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("permission_id", pg.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
        sa.Index("ix_role_permission_role_id", "role_id"),
        sa.Index("ix_role_permission_permission_id", "permission_id"),
    )

    # Refresh tokens
    op.create_table(
        "refresh_tokens",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", pg.BYTEA, nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("(now())"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "revoked", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("user_id", pg.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.Index("ix_refresh_tokens_user_id", "user_id"),
    )

    # Audit events (immutable)
    op.create_table(
        "audit_events",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("(now())"),
        ),
        sa.Column("user_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "decision", sa.Enum("PERMIT", "DENY", name="decision_enum"), nullable=False
        ),
        sa.Column("permission_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("deny_reason", sa.String(length=50), nullable=True),
        sa.Column("context_snapshot", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("client_type", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.Index("ix_audit_events_user_id", "user_id"),
        sa.Index("ix_audit_events_resource_id", "resource_id"),
        sa.Index("ix_audit_events_permission_id", "permission_id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.drop_table("audit_events")
    op.drop_table("refresh_tokens")
    op.drop_table("role_permission")
    op.drop_table("user_role")
    op.drop_table("permissions")
    op.drop_table("resources")
    op.drop_table("roles")
    op.drop_table("users")
    # ### end Alembic commands ###
