"""drop_audit_events_resource_id_fk

Revision ID: d86555ec6820
Revises: 0001_initial
Create Date: 2026-05-02 02:48:50.425605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86555ec6820'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.drop_constraint('audit_events_resource_id_fkey', 'audit_events', type_='foreignkey')
    op.drop_index('ix_resources_name', table_name='resources')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.create_index('ix_resources_name', 'resources', ['name'], unique=False)
    op.create_foreign_key('audit_events_resource_id_fkey', 'audit_events', 'resources', ['resource_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    # ### end Alembic commands ###
